version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: finance-tracker-db
    environment:
      POSTGRES_DB: personal-finance-tracker
      POSTGRES_USER: personal_finance_tracker_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-demo_password_123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U personal_finance_tracker_user -d personal-finance-tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: finance-tracker-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/personal-finance-tracker
      SPRING_DATASOURCE_USERNAME: personal_finance_tracker_user
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-demo_password_123}
      JWT_SECRET: ${JWT_SECRET:-fallbackSecretKeyThatIsSecureAndItIsLeast256BitsLongForSure}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
